SELECT A.ID AS 'ID'
     , IFNULL(B.COUNT, 0) AS 'CHILD_COUNT' 
FROM ECOLI_DATA A 
LEFT JOIN (
    SELECT PARENT_ID AS 'ID'
         , COUNT(*) AS 'COUNT' 
    FROM ECOLI_DATA 
    GROUP BY 1) B
ON A.ID = B.ID
ORDER BY 1 ASC