# '세단'or'SUV'
# 2022년11월1일~11월30일 대여가능
# 50만원 <= 30일대여금액 < 200만원
# CAR_ID, CAR_TYPE, FEE (3 DESC, 2 ASC, 1 DESC)

SELECT C.CAR_ID AS CAR_ID,
       C.CAR_TYPE AS CAR_TYPE,
       ROUND(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01'
    ) AND D.DURATION_TYPE LIKE '30%'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV') 
    AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY 3 DESC, 2 ASC, 1 DESC