SELECT S.SCORE, S.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E INNER JOIN (
        SELECT SUM(SCORE) AS SCORE, EMP_NO
        FROM HR_GRADE 
        WHERE YEAR = 2022
        GROUP BY EMP_NO
        ORDER BY SUM(SCORE) DESC
        LIMIT 1
        ) AS S ON E.EMP_NO = S.EMP_NO
