# 우선 각 연도별 가장 큰 대장균의 크기를 구한 테이블 생성(YEAR_MAX)
WITH YEAR_MAX AS (
    SELECT MAX(SIZE_OF_COLONY) AS 'MAX_SIZE'
        , YEAR(DIFFERENTIATION_DATE) AS 'MAX_YEAR'
    FROM ECOLI_DATA 
    GROUP BY 2
)
# 분화연도, 분화된 연도별 대장균 크기 편차, 대장균 개체 ID 테이블
SELECT YEAR(E.DIFFERENTIATION_DATE) AS 'YEAR'
    , (M.MAX_SIZE - E.SIZE_OF_COLONY) AS 'YEAR_DEV'
    , E.ID
FROM ECOLI_DATA AS E JOIN YEAR_MAX AS M 
ON YEAR(E.DIFFERENTIATION_DATE) = M.MAX_YEAR
ORDER BY 1 ASC, 2 ASC