SELECT P.PRODUCT_CODE, P.PRICE * S.SA AS SALES
FROM PRODUCT AS P 
INNER JOIN (
SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SA
FROM OFFLINE_SALE 
GROUP BY PRODUCT_ID
) AS S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY 1
ORDER BY 2 DESC, 1 ASC