WITH D AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE, C.CAR_TYPE,
           DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS 'PERIOD',
           CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE '7일 미만' END AS 'DURATION_TYPE'
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID
    WHERE CAR_TYPE = '트럭'
    )
    
SELECT D.HISTORY_ID,
       ROUND(D.DAILY_FEE * D.PERIOD * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS 'FEE'
FROM D LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON P.DURATION_TYPE = D.DURATION_TYPE AND P.CAR_TYPE = D.CAR_TYPE
ORDER BY 2 DESC, 1 DESC