SELECT CATEGORY, SUM(CS) AS TOTAL_SALES
FROM BOOK B LEFT JOIN
(
SELECT BOOK_ID, SUM(SALES) AS CS
FROM BOOK_SALES 
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID
ORDER BY BOOK_ID
) C ON B.BOOK_ID = C.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY