SELECT FLAVOR
FROM
(
SELECT J.SHIPMENT_ID, J.FLAVOR, 
       SUM(J.TOTAL_ORDER) AS JTOTAL,
       SUM(F.TOTAL_ORDER) AS FTOTAL,
       SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER) AS TOTAL
FROM JULY J LEFT JOIN FIRST_HALF F ON J.SHIPMENT_ID = F.SHIPMENT_ID
GROUP BY J.FLAVOR
)T
ORDER BY TOTAL DESC
LIMIT 3